{{- $releaseName := .Release.Name}}
{{- range $key := .Values.node.keys}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{$releaseName}}-{{$key.type}}
stringData:
  type: {{$key.type}}
  scheme: {{$key.scheme}}
  seed: {{$key.seed}}
{{- end }}