apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-peer
  labels:
    {{- include "infra-para.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.rpc }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.peer }}
      targetPort: peer
      protocol: TCP
      name: peer
  selector:
    {{- include "infra-para.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-headless
  labels:
    {{- include "infra-para.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.rpc }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.peer }}
      targetPort: peer
      protocol: TCP
      name: peer
  selector:
    {{- include "infra-para.selectorLabels" . | nindent 4 }}