apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-explorer-db-secret
type: Opaque
data:
  DB_PASSWORD: {{ .Values.reader.config.db.password }}
  API_SQLA_URI: {{ .Values.reader.config.db.sqlaUrl }}
  DB_CONNECTION: {{ .Values.reader.config.db.connection }}
